// Exporters for a processed take: a JSON show file, a CSV for spreadsheets /
// plotting, and a self-contained Arduino sketch that plays the take back on
// a PCA9685 16-channel servo driver.

import { angleToMicros, type ChannelSpec } from "./channels"
import type { ProcessedTake } from "./pipeline"

const round2 = (x: number) => Math.round(x * 100) / 100

export function toShowJson(take: ProcessedTake, channels: ChannelSpec[], name: string) {
  const frames: number[][] = []
  for (let i = 0; i < take.frameCount; i++) frames.push(channels.map((c) => round2(take.tracks[c.id].output[i])))
  return JSON.stringify(
    {
      format: "motion-studio/1",
      name,
      rate: take.rate,
      frameCount: take.frameCount,
      channels: channels.map((c) => ({
        key: c.key,
        label: c.label,
        unit: "deg",
        min: c.min,
        max: c.max,
        vmax: c.vmax,
        amax: c.amax,
        jmax: c.jmax,
        minUs: c.minUs,
        maxUs: c.maxUs,
      })),
      frames,
    },
    null,
    0,
  )
}

export function toCsv(take: ProcessedTake, channels: ChannelSpec[]) {
  const rows = [["time_s", ...channels.map((c) => c.key)].join(",")]
  for (let i = 0; i < take.frameCount; i++) {
    rows.push([(i / take.rate).toFixed(3), ...channels.map((c) => take.tracks[c.id].output[i].toFixed(2))].join(","))
  }
  return rows.join("\n")
}

export function toArduinoSketch(take: ProcessedTake, channels: ChannelSpec[], name: string) {
  const frameMs = Math.round(1000 / take.rate)
  const bytes = take.frameCount * channels.length * 2
  const frameLines: string[] = []
  for (let i = 0; i < take.frameCount; i++) {
    const us = channels.map((c) => angleToMicros(c, take.tracks[c.id].output[i]))
    frameLines.push(`  {${us.join(", ")}},`)
  }

  return `// ${name}.ino — generated by Motion Studio (ethn archive)
//
// Plays a ${take.duration.toFixed(2)} s animatronic take (${take.frameCount} frames @ ${take.rate} Hz,
// ${channels.length} channels) on a PCA9685 servo driver over I2C. Every frame has
// already been run through a jerk-limited motion profile, so the playback
// loop only has to send pulses — no filtering on the microcontroller.
//
// Wiring: PCA9685 SDA/SCL -> board I2C, V+ -> separate 5-6 V servo supply.
// Channel N on the driver = column N below.
// Needs: Adafruit PWM Servo Driver Library (Library Manager).
// Frame table: ${bytes.toLocaleString("en-US")} bytes of flash (fits an Uno at <= ~1,400 frames; ESP32 has room to spare).

#include <Wire.h>
#include <Adafruit_PWMServoDriver.h>

Adafruit_PWMServoDriver pwm = Adafruit_PWMServoDriver();

const uint8_t CHANNELS = ${channels.length};
const uint16_t FRAMES = ${take.frameCount};
const uint16_t FRAME_MS = ${frameMs};
const bool LOOP_SHOW = true;

// Channel order: ${channels.map((c) => c.key).join(", ")}
// Neutral pulse per channel, sent at power-up and between loops.
const uint16_t NEUTRAL_US[CHANNELS] = {${channels.map((c) => angleToMicros(c, c.neutral)).join(", ")}};

// Pulse widths in microseconds, one row per frame.
const uint16_t SHOW[FRAMES][CHANNELS] PROGMEM = {
${frameLines.join("\n")}
};

void writeFrame(uint16_t f) {
  for (uint8_t c = 0; c < CHANNELS; c++) {
    pwm.writeMicroseconds(c, pgm_read_word(&SHOW[f][c]));
  }
}

void setup() {
  pwm.begin();
  pwm.setOscillatorFrequency(27000000);
  pwm.setPWMFreq(50);
  delay(10);
  for (uint8_t c = 0; c < CHANNELS; c++) pwm.writeMicroseconds(c, NEUTRAL_US[c]);
  delay(1000);
}

void loop() {
  static uint16_t frame = 0;
  static uint32_t next = millis();

  // Fixed-rate playback: schedule against the clock, not delay(), so frame
  // time doesn't drift with I2C write time.
  if ((int32_t)(millis() - next) < 0) return;
  next += FRAME_MS;

  writeFrame(frame);
  if (++frame >= FRAMES) {
    frame = 0;
    if (!LOOP_SHOW) while (true) {}
    delay(1500);
    next = millis();
  }
}
`
}

export function downloadText(filename: string, text: string, type = "text/plain") {
  const url = URL.createObjectURL(new Blob([text], { type }))
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
